### PR TITLE
fix for issue #351

### LINKED ISSUE #351: Session Numbers increase when on hold caller disconnects
In the new developer version, the session number has been fixed (for the most part). I have noticed if you put someone on hold & the call disconnects, the next time you receive/make a call, the session # increases by 1. The only way to fix it is 'core restart now'.

**Reproduction Steps:**

1. Call phone (ie. 211)  and put call on hold
2. Hangup phone you made the initial call on (ie. 210)
3. Call the phone you answered on the first time (211)
4. Notice the increased session number

**Expected behavior:**

If caller disconnects while on hold, channel should hangup & session number will return to 1

**Observed behavior:**

When on-hold caller disconnects, the session number increases by 1.

**Screenshots**

(Screenshots which show reproduction steps and/or demonstrate the problem)

https://youtu.be/8oqd-13RXwY

**chan-sccp version:** Release: 4.3.0 develop - 12f96a9M 

**asterisk version:** 13
**Addition / Optional Information:**
* Problem started happening recently, didn't happen in an older version of Chan-SCCP: [Yes/No] Not Sure
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
* Platform:
    * [CPU]
    * [32/64 Bit]
    * [Big/Small Endian]
    * [Operating System]
    * [Operating System Version]
* Direct Contact information: [You can contact me here]
* Log Files (attach .txt / [pastbin](http://pastebin.com/) / [gist](http://gist.github.com/)): [url]
* Comments: [Other Information]
*

### PR DESCRIPTION
**Pull request by marcelloceschia**
Closes #351.

Changes proposed by this Pull Request:
- decrement the numberOfHeldChannels on hangup (moved from channel to pbx)

Inform: @dkgroot 

@Glasswire can you chechout branch issue/351 and check if this fixes your issue? Thank you

### CODE REVIEW

**Comment by dkgroot** [comment]
Would have been nicer if the decrement would have stayed in the src (preferably sccp_line.c or sccp_channel.c) directory and not be moved to pbx_impl. 

If we move l->statistic.numberOfHeldChannels++ and l->statistic.numberOfHeldChannels-- to the sccp_dev_setActiveLine() using channel->state == AST_CHANNELSTATE_HOLD, we should be able to correct this.

Logically sccp_dev_setActiveLine is always called during channel hangup and or destruction (to keep the refcount correct), so this location would be idea. We will have to set the channel->state to the correct value before it is being called during channel_hold and channel_resume, to that the right action is taken.

I don't mind this patch if it solves the issue for now.

FYI: would have been nice if sccp_indicate was constructed as a state-machine instead of the big switch-case we have now :-)

**Comment by marcelloceschia** [comment]
@dkgroot if the channel is HOLD there is no device connected to this line `sccp_dev_setActiveLine(d, NULL);` and `sccp_channel_setDevice(channel, NULL);` 
So how you would distinguish between hangup and hold?

**Comment by dkgroot** [comment]
in sccp_channel_hold we can do this:
```
sccp_indicate(d, channel, SCCP_CHANNELSTATE_HOLD);
sccp_dev_setActiveLine(d, NULL);    // will also call sccp_channel_setDevice in the process
```

in sccp_channel_resume (we know where we are going to resume):
```
// make sure the channel->state is HOLD, so we can test for it.
channel->state = SCCP_CHANNELSTATE_HOLD    // (not sure if required)
sccp_channel_setDevice(channel, d);
```

in sccp_channel_setDevice(channel, device)
```
// channel is on hold and we are removing device (either resume or hangup)
if(!device && channel->state == SCCP_CHANNELSTATE_HOLD && channel->privateData->device) {
     channel->line->statistic.numberOfHeldChannels--;
}
...
// orig code
sccp_device_refreplace(&channel->privateData->device, (sccp_device_t *) device);
...
// sccp_channel_resume is calling use (with a fake/non-indicated channel state) and assigning a new device
if (device && channel->state == SCCP_CHANNELSTATE_HOLD && channel->privateData->device) {
     channel->line->statistic.numberOfHeldChannels++;
}
```

**Comment by marcelloceschia** [comment]
@dkgroot but does this solve this issue, where the remote channel requests a hangup for a channel thats on hold?

**Comment by dkgroot** [comment]
Have not checked/tried or tested, but i think it should. We would have to check sccp_channel_cleanup, sccp_channel_destroy and sccp_channel_transfer_release to make sure, we do the right thing in all instances.
I don't want to mess up you pull request / branch, so might be easier for your to check/test.

**Comment by marcelloceschia** [comment]
@dkgroot please check the latest version

**Comment by dkgroot** [comment]
That makes sense :-) Did you have time to check and test ? Should we merge it ?

**Comment by Glasswire** [comment]
I hate to ask this, but how do you apply the fixes you've made in the 
link you sent me?

https://github.com/chan-sccp/chan-sccp/pull/352/commits/55a0dcd9e000892f1931587798ef84a892de5e05


Thanks!

**Comment by marcelloceschia** [comment]
@Glasswire 

with your current chan-sccp directory
``` 
git fetch origin
git checkout -b 'issue/351' origin/issue/351
./configure && make && make install && asterisk -rx "module unload chan_sccp.so" && asterisk -rx "module load chan_sccp.so"
``` 

or with a new directory:

``` 
git clone https://github.com/chan-sccp/chan-sccp.git chan-sccp_issue352
cd chan-sccp_issue352
git checkout -b issue/351 origin/issue/351
./configure && make && make install && asterisk -rx "module unload chan_sccp.so" && asterisk -rx "module load chan_sccp.so"
```

**Comment by dkgroot** [comment]
@marcelloceschia Sorry about the issue with the Makefile :-(

**Comment by Glasswire** [comment]
I'm getting this error towards the end of running the last command

Unable to unload resource chan_sccp.so
Command 'module unload chan_sccp.so' failed.
Unable to load module chan_sccp.so
Command 'module load chan_sccp.so' failed.

**Comment by dkgroot** [comment]
@glasswire: Skip the last part of both commands and just do that manually. Check the asterisk CLI to see why it's complaining. Marcello only added those commands only as a convenience.

Note: If you do want to do a reload the module after running make install you can do:
make && make install && make reload
If something goes wrong however do these steps manually and check what's going on.

**Comment by Glasswire** [comment]
It worked!

**Comment by dkgroot** [comment]
@marcelloceschia sorry for butting in, but you managed to come up with a much nicer solution in the end. Thanks

**Pull request merged**
